#!/usr/bin/env bash

###############################################################################
#
#   Master script to generate template-based text files
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 21-09-2019
#   LICENSE: Apache_2.0
#   USAGE: bash template <FILENAME>
#
###############################################################################

# define the global variables
AUTHOR="Maciej_Bak"
AFFILIATION="Swiss_Institute_of_Bioinformatics"
EMAIL="wsciekly.maciek@gmail.com"
DATE=$(date +"%d-%m-%Y")
LICENSE="Apache_2.0"

# check for the correct call
if [ $# -ge 2 ]; then
    echo "Incorrect call; please provide file name only.";
    exit;
fi

# check if file already exists
if test -f "$1"; then
    echo "File already exists.";
    exit;
fi

# create the substitution command for sed
SED_COMMAND="\
-e s/{AUTHOR}/$AUTHOR/g \
-e s/{AFFILIATION}/$AFFILIATION/g \
-e s/{EMAIL}/$EMAIL/g \
-e s/{DATE}/$DATE/g \
-e s/{LICENSE}/$LICENSE/g \
"

# match the file name against extensions
case $(echo "$1" | cut -d . -f2) in

    c) # C file with implementation
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.c \
            >"$1" ;;

    cpp) # C++ file with implementation
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.cpp \
            >"$1" ;;

    h) # header file
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.h \
            >"$1" ;;

    py) # Python script
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.py \
            >"$1" ;;

    r) # R script
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.r \
            >"$1" ;;

    R) # R script
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.r \
            >"$1" ;;

    sh) # shell script
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.sh \
            >"$1" ;;

    yml) # yaml file
        sed $SED_COMMAND \
            <"$(dirname "$0")"/templates/template.yml \
            >"$1" ;;

    *) #other files
        echo "Template undefined." ;;

esac
